# run with "docker compose up -d"

services:
  postgres:
    image: postgres:17
    restart: always
    volumes:
      - ./scratch/postgres-data:/var/lib/postgresql/data
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=TestSecreto
      - POSTGRES_DB=sandbox
    ports:
      - "54322:5432"
